name: Test SingleM with Setup-Miniconda From Marketplace
on: [push]

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: singlem.yml
          python-version: 3.6
          auto-activate-base: false
          mamba-version: "*"
          channels: conda-forge,defaults,bioconda,masonite
      - run: |
          conda info
          conda list
      - name: Run pytest
        run: |
            python test/test_metapackage.py && \
            python test/test_makedb_and_query.py && \
            python test/test_condense.py && \
            python test/test_summariser.py
